route:
  # group_by: ['alertname']
  # group_wait: 10s
  # group_interval: 1m
  repeat_interval: 1m
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        username: 'AlertManager'
        channel: '#alertmanaget-test'
        api_url: 'https://hooks.slack.com/services/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'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        # title: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
        text: "<!channel> \n*Alert:* {{ .GroupLabels.alertname }} - `{{ .CommonLabels.severity }}`\n*Description:* {{ .CommonAnnotations.description }}"