groups:
  - name: alert_rules
    rules:
      # - alert: Dagster Unreachable
      #   expr: probe_success{instance="http://192.168.1.100:8080"} == 0
      #   for: 30s
      #   labels:
      #     severity: critical
      #   annotations:
      #     # summary: "Dasgter is Down"
      #     description: "Dagster container crashed"

      - alert: High CPU Utilization
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 10
        for: 1m  # Optional: Specify how long the condition must persist before triggering an alert
        labels:
          severity: warning
        annotations:
          # summary: "High CPU Utilization"
          description: "The CPU utilization is above 70% on instance {{$labels.instance}}"